apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: proxy-app
  name: proxy-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: proxy-app
  template:
    metadata:
      labels:
        app: proxy-app
    spec:
      containers:
      - image: jjmmyyou111/study:proxy-app
        name: proxy-app
        env:
        - name: API_URL
          value: "http://hello-app-service.helloworld"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-app-service
spec:
  selector:
    app: proxy-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000